export default {
  '-- layout': {
    type: 'separator',
    title: 'Layout',
  },
  accordion: 'Accordion',
  'aspect-ratio': 'AspectRatio',
  card: 'Card',
  divider: 'Divider',
  'infinite-scroll': 'InfiniteScroll',
  list: 'List',
  'resizable-panels': 'ResizablePanels',
  'scroll-area': 'ScrollArea',
  skeleton: 'Skeleton',
  virtualizer: 'Virtualizer',
  '-- feedback': {
    type: 'separator',
    title: 'Feedback',
  },
  alert: 'Alert',
  badge: 'Badge',
  'empty-state': 'EmptyState',
  'progress-bar': 'ProgressBar',
  rating: 'Rating',
  spinner: 'Spinner',
  stat: 'Stat',
  '-- forms': {
    type: 'separator',
    title: 'Forms',
  },
  button: 'Button',
  calendar: 'Calendar',
  checkbox: 'Checkbox',
  'color-picker': 'ColorPicker',
  combobox: 'Combobox',
  'date-picker': 'DatePicker',
  editable: 'Editable',
  'file-upload': 'FileUpload',
  form: 'Form',
  input: 'Input',
  'number-input': 'NumberInput',
  otp: 'OTP',
  password: 'Password',
  radio: 'Radio',
  'rich-text': 'RichText',
  select: 'Select',
  slider: 'Slider',
  switch: 'Switch',
  tag: 'Tag',
  'tag-input': 'TagInput',
  textarea: 'Textarea',
  toggle: 'Toggle',
  '-- navigation': {
    type: 'separator',
    title: 'Navigation',
  },
  breadcrumb: 'Breadcrumb',
  'menu-bar': 'MenuBar',
  'navigation-menu': 'NavigationMenu',
  pagination: 'Pagination',
  stepper: 'Stepper',
  tabs: 'Tabs',
  toolbar: 'Toolbar',
  'tree-view': 'TreeView',
  '-- overlays': {
    type: 'separator',
    title: 'Overlays',
  },
  command: 'Command',
  'context-menu': 'ContextMenu',
  drawer: 'Drawer',
  dropdown: 'Dropdown',
  'hover-card': 'HoverCard',
  modal: 'Modal',
  popover: 'Popover',
  search: 'Search',
  sheet: 'Sheet',
  toast: 'Toast',
  tooltip: 'Tooltip',
  '-- media': {
    type: 'separator',
    title: 'Media',
  },
  avatar: 'Avatar',
  carousel: 'Carousel',
  icon: 'Icon',
  image: 'Image',
  timeago: 'Timeago',
  '-- ai': {
    type: 'separator',
    title: 'AI',
  },
  chat: 'Chat',
  citation: 'Citation',
  'code-block': 'CodeBlock',
  diff: 'Diff',
  markdown: 'Markdown',
  mention: 'Mention',
  typewriter: 'Typewriter',
}
