export default {
  '-- layout': {
    type: 'separator',
    title: 'Layout',
  },
  accordion: 'Accordion',
  card: 'Card',
  divider: 'Divider',
  list: 'List',
  '-- feedback': {
    type: 'separator',
    title: 'Feedback',
  },
  alert: 'Alert',
  badge: 'Badge',
  'progress-bar': 'ProgressBar',
  rating: 'Rating',
  '-- forms': {
    type: 'separator',
    title: 'Forms',
  },
  button: 'Button',
  checkbox: 'Checkbox',
  input: 'Input',
  otp: 'OTP',
  password: 'Password',
  radio: 'Radio',
  select: 'Select',
  switch: 'Switch',
  textarea: 'Textarea',
  '-- overlays': {
    type: 'separator',
    title: 'Overlays',
  },
  drawer: 'Drawer',
  dropdown: 'Dropdown',
  modal: 'Modal',
  search: 'Search',
  tooltip: 'Tooltip',
  '-- media': {
    type: 'separator',
    title: 'Media',
  },
  avatar: 'Avatar',
  icon: 'Icon',
  image: 'Image',
  timeago: 'Timeago',
}
