export default {
  '-- layout': {
    type: 'separator',
    title: 'Layout',
  },
  accordion: 'Accordion',
  'aspect-ratio': 'AspectRatio',
  card: 'Card',
  divider: 'Divider',
  list: 'List',
  'resizable-panels': 'ResizablePanels',
  skeleton: 'Skeleton',
  '-- feedback': {
    type: 'separator',
    title: 'Feedback',
  },
  alert: 'Alert',
  badge: 'Badge',
  'progress-bar': 'ProgressBar',
  rating: 'Rating',
  spinner: 'Spinner',
  '-- forms': {
    type: 'separator',
    title: 'Forms',
  },
  button: 'Button',
  calendar: 'Calendar',
  checkbox: 'Checkbox',
  combobox: 'Combobox',
  'date-picker': 'DatePicker',
  'file-upload': 'FileUpload',
  form: 'Form',
  input: 'Input',
  'number-input': 'NumberInput',
  otp: 'OTP',
  password: 'Password',
  radio: 'Radio',
  select: 'Select',
  slider: 'Slider',
  switch: 'Switch',
  tag: 'Tag',
  'tag-input': 'TagInput',
  textarea: 'Textarea',
  '-- navigation': {
    type: 'separator',
    title: 'Navigation',
  },
  breadcrumb: 'Breadcrumb',
  'menu-bar': 'MenuBar',
  'navigation-menu': 'NavigationMenu',
  pagination: 'Pagination',
  tabs: 'Tabs',
  'tree-view': 'TreeView',
  '-- overlays': {
    type: 'separator',
    title: 'Overlays',
  },
  'context-menu': 'ContextMenu',
  drawer: 'Drawer',
  dropdown: 'Dropdown',
  modal: 'Modal',
  popover: 'Popover',
  search: 'Search',
  toast: 'Toast',
  tooltip: 'Tooltip',
  '-- media': {
    type: 'separator',
    title: 'Media',
  },
  avatar: 'Avatar',
  icon: 'Icon',
  image: 'Image',
  timeago: 'Timeago',
}
